language: c
install:
  - wget http://mirror.rise.ph/gnu/gsl/gsl-2.4.tar.gz
  - tar xvzf gsl-2.4.tar.gz
  - cd gsl-2.4
  - ./configure && make && sudo make install
  - cd ..
compiler:
  - clang
  - gcc
script:
  - make
  - make -f makefile.pthread
  - make -f makefile.sse3.pthread
  - make -f makefile.sse3.openmp
  - make -f makefile.openmp
  - make -f makefile.sse3
