/*
 *  modelAveraging.c
 *  physher
 *
 *  Created by Mathieu Fourment on 27/6/12.
 *  Copyright (C) 2016 Mathieu Fourment. All rights reserved.
 *
 *  This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 *  of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along with this program; if not,
 *  write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include <stdio.h>
#include <string.h>

#include "phyc/args.h"
#include "phyc/modelavg.h"
#include "phyc/tree.h"
#include "phyc/treeio.h"
#include "phyc/treelogio.h"



int main(int argc, char* argv[]){
    
    if ( argc == 1 || args_get_boolean(argc, argv, "-h") || args_get_boolean(argc, argv, "--help") ) {
        printf("\nModel average trees generated by a genetic algorithm from Physher\n\n");
        printf("Command options\n\n");
        printf(" -i file containing trees generated by a genetic algorithm [REQUIRED]\n");
        printf(" -o output tree file [REQUIRED]\n");
        printf(" -p confidence level [default: 0.95]\n");
        printf("\n");
        printf("Example\n\n");
        printf("./modelavg -i file.disccrete.ga.trees -o file.strict.boot.tree -p 0.95\n\n");
        exit(0);
    }
    
    char *infile  = NULL;
	char *outfile = NULL;
	double p = 0.95; // 95% conficence interval
    int nclasses = -1;
    
    if ( args_contains(argc, argv, "-i") ) {
        infile = args_get_string(argc, argv, "-i");
    }
    else {
        error("Need an input tree file [-i]\n");
    }
    
    if ( args_contains(argc, argv, "-o") ) {
        outfile = args_get_string(argc, argv, "-o");
    }
    else {
        error("Need an output file name [-o]\n");
    }
	
    if ( args_contains(argc, argv, "-c") ) {
        bool success = false;
        nclasses = args_get_int2(argc, argv, "-c", &success );
        if( !success || nclasses <= 0 ){
            error("Could not read the number of classes [-c]");
        }
    }
	
    if ( args_contains(argc, argv, "-p") ) {
        bool success = false;
        p = args_get_double(argc, argv, "-p", &success );
        if( !success || p <= 0 ){
            error("Could not read significance level [-p]");
        }
    }
	
	char **orderedNames = NULL;
	int start = 0;
	int end = 0;
    if(nclasses == -1 ){
        end = 100000000;
    }
    else if( nclasses != 0 ){
        TreeLog_define_range_nclasses(infile, nclasses, &start, &end);
    }
    else{
        nclasses = TreeLog_define_range(infile, &start, &end, 0.05);
    }
    
    
	fprintf(stderr, "\n. Number of rates %d\n", nclasses);
	fprintf(stderr, ". Tree range %d %d\n", start, end);
	
	Tree *tree = Model_average_from_log( infile, p, &orderedNames, start, end );
		
	FILE *file = fopen(outfile,"w");
    Tree_print_nexus_header_figtree_Taxa(file, tree);
    Tree_print_nexus_header_figtree_BeginTrees(file, tree);
    fprintf(file, "tree TREE0 = [&R] ");
    Tree_print_nexus_with_annotation( file, tree );
    fprintf(file, "\nEnd;");

	fclose(file);
    
	free_Tree(tree);
    for ( int i = 0 ; i < Tree_tip_count(tree); i++ ) {
        free(orderedNames[i]);
    }
    free(orderedNames);
    free(infile);
    free(outfile);
	
	return 0;
}
